export const countries = [
  { name: 'Australia', flag: '🇦🇺', code: 'au', counsellors: 24 },
  { name: 'Canada', flag: '🇨🇦', code: 'ca', counsellors: 31 },
  { name: 'United Kingdom', flag: '🇬🇧', code: 'gb', counsellors: 18 },
  { name: 'USA', flag: '🇺🇸', code: 'us', counsellors: 27 },
  { name: 'Japan', flag: '🇯🇵', code: 'jp', counsellors: 12 },
  { name: 'Germany', flag: '🇩🇪', code: 'de', counsellors: 9 },
  { name: 'New Zealand', flag: '🇳🇿', code: 'nz', counsellors: 15 },
  { name: 'South Korea', flag: '🇰🇷', code: 'kr', counsellors: 8 },
]

export const consultancies = [
  {
    id: 1,
    name: 'Global Reach Education',
    logo: 'GR',
    location: 'Kathmandu',
    counsellors: 8,
    rating: 4.8,
    reviews: 142,
    featured: true,
    heroBanner: true,
    countries: ['Australia', 'Canada', 'UK'],
    tagline: 'Your gateway to world-class education',
    color: '#2563EB',
    verified: true,
  },
  {
    id: 2,
    name: 'EduPath Consultancy',
    logo: 'EP',
    location: 'Pokhara',
    counsellors: 5,
    rating: 4.6,
    reviews: 98,
    featured: true,
    heroBanner: false,
    countries: ['USA', 'Canada', 'Australia'],
    tagline: 'Charting your future, one visa at a time',
    color: '#06B6D4',
    verified: true,
  },
  {
    id: 3,
    name: 'Abroad Dreams Nepal',
    logo: 'AD',
    location: 'Kathmandu',
    counsellors: 6,
    rating: 4.7,
    reviews: 115,
    featured: true,
    heroBanner: false,
    countries: ['Japan', 'South Korea', 'Germany'],
    tagline: 'Making your abroad dreams a reality',
    color: '#7C3AED',
    verified: true,
  },
  {
    id: 4,
    name: 'Visa Pro Nepal',
    logo: 'VP',
    location: 'Lalitpur',
    counsellors: 4,
    rating: 4.5,
    reviews: 76,
    featured: false,
    heroBanner: false,
    countries: ['UK', 'Germany', 'New Zealand'],
    tagline: 'Expert visa guidance since 2015',
    color: '#059669',
    verified: true,
  },
  {
    id: 5,
    name: 'Future Scholars',
    logo: 'FS',
    location: 'Bhaktapur',
    counsellors: 3,
    rating: 4.4,
    reviews: 54,
    featured: false,
    heroBanner: false,
    countries: ['Australia', 'New Zealand'],
    tagline: 'Scholarships and admissions made easy',
    color: '#DC2626',
    verified: false,
  },
]

export const counsellors = [
  {
    id: 1,
    name: 'Priya Sharma',
    photo: 'https://randomuser.me/api/portraits/women/32.jpg',
    consultancy: 'Global Reach Education',
    consultancyId: 1,
    countries: ['Australia', 'Canada'],
    experience: 6,
    languages: ['Nepali', 'English', 'Hindi'],
    rating: 4.9,
    reviews: 67,
    students: 234,
    whatsapp: '9779841234567',
    bio: 'Specialized in Australian university admissions with 6 years of experience helping students secure placements in top universities.',
    verified: true,
  },
  {
    id: 2,
    name: 'Rohan Thapa',
    photo: 'https://randomuser.me/api/portraits/men/45.jpg',
    consultancy: 'Global Reach Education',
    consultancyId: 1,
    countries: ['UK', 'Canada'],
    experience: 4,
    languages: ['Nepali', 'English'],
    rating: 4.7,
    reviews: 45,
    students: 178,
    whatsapp: '9779841234568',
    bio: 'UK student visa specialist with strong relationships with Russell Group universities.',
    verified: true,
  },
  {
    id: 3,
    name: 'Sita Gurung',
    photo: 'https://randomuser.me/api/portraits/women/68.jpg',
    consultancy: 'EduPath Consultancy',
    consultancyId: 2,
    countries: ['USA', 'Canada'],
    experience: 8,
    languages: ['Nepali', 'English', 'Newari'],
    rating: 4.8,
    reviews: 89,
    students: 312,
    whatsapp: '9779841234569',
    bio: 'IELTS certified counsellor with expertise in US university applications and scholarship hunting.',
    verified: true,
  },
  {
    id: 4,
    name: 'Bikash Rai',
    photo: 'https://randomuser.me/api/portraits/men/22.jpg',
    consultancy: 'Abroad Dreams Nepal',
    consultancyId: 3,
    countries: ['Japan', 'South Korea'],
    experience: 5,
    languages: ['Nepali', 'English', 'Japanese'],
    rating: 4.9,
    reviews: 52,
    students: 189,
    whatsapp: '9779841234570',
    bio: 'Japan language school and university specialist. JLPT N2 certified with deep knowledge of Japanese education system.',
    verified: true,
  },
  {
    id: 5,
    name: 'Anita Maharjan',
    photo: 'https://randomuser.me/api/portraits/women/44.jpg',
    consultancy: 'Visa Pro Nepal',
    consultancyId: 4,
    countries: ['UK', 'Germany'],
    experience: 7,
    languages: ['Nepali', 'English', 'German'],
    rating: 4.6,
    reviews: 38,
    students: 156,
    whatsapp: '9779841234571',
    bio: 'German university admissions expert offering guidance for both English and German taught programs.',
    verified: true,
  },
  {
    id: 6,
    name: 'Suraj Pandey',
    photo: 'https://randomuser.me/api/portraits/men/56.jpg',
    consultancy: 'Future Scholars',
    consultancyId: 5,
    countries: ['Australia', 'New Zealand'],
    experience: 3,
    languages: ['Nepali', 'English'],
    rating: 4.5,
    reviews: 29,
    students: 97,
    whatsapp: '9779841234572',
    bio: 'Young and passionate counsellor focused on scholarship opportunities in Australia and New Zealand.',
    verified: false,
  },
]

export const reviews = [
  {
    id: 1,
    student: 'Aarav K.',
    counsellor: 'Priya Sharma',
    country: 'Australia',
    university: 'University of Melbourne',
    rating: 5,
    text: 'Priya was incredibly helpful throughout my application process. Got into my dream university!',
    willVisit: true,
    wasHelpful: true,
    date: '2024-11-15',
  },
  {
    id: 2,
    student: 'Manisha T.',
    counsellor: 'Sita Gurung',
    country: 'USA',
    university: 'University of Texas',
    rating: 5,
    text: 'The entire process from application to visa was smooth. Highly recommend EduPath.',
    willVisit: true,
    wasHelpful: true,
    date: '2024-10-22',
  },
  {
    id: 3,
    student: 'Dipesh B.',
    counsellor: 'Bikash Rai',
    country: 'Japan',
    university: 'Waseda University',
    rating: 5,
    text: 'Bikash helped me with my Japanese language school application. Now studying in Tokyo!',
    willVisit: true,
    wasHelpful: true,
    date: '2024-12-01',
  },
]

export const analytics = {
  totalVisitors: 12847,
  totalLogins: 4231,
  totalLeads: 1876,
  totalWhatsappClicks: 1543,
  conversionRate: 36.4,
  topCountries: [
    { country: 'Australia', leads: 524 },
    { country: 'Canada', leads: 412 },
    { country: 'USA', leads: 387 },
    { country: 'UK', leads: 298 },
    { country: 'Japan', leads: 255 },
  ],
  leadsPerConsultancy: [
    { name: 'Global Reach', leads: 487 },
    { name: 'EduPath', leads: 398 },
    { name: 'Abroad Dreams', leads: 312 },
    { name: 'Visa Pro', leads: 234 },
    { name: 'Future Scholars', leads: 145 },
  ],
  recentLeads: [
    { id: 1, student: 'Ram Prasad', destination: 'Australia', course: 'MBA', counsellor: 'Priya Sharma', consultancy: 'Global Reach', date: '2024-12-10', status: 'new' },
    { id: 2, student: 'Srijana KC', destination: 'Canada', course: 'Computer Science', counsellor: 'Rohan Thapa', consultancy: 'Global Reach', date: '2024-12-10', status: 'contacted' },
    { id: 3, student: 'Niraj Shrestha', destination: 'USA', course: 'Engineering', counsellor: 'Sita Gurung', consultancy: 'EduPath', date: '2024-12-09', status: 'new' },
    { id: 4, student: 'Puja Tamang', destination: 'Japan', course: 'Language Course', counsellor: 'Bikash Rai', consultancy: 'Abroad Dreams', date: '2024-12-09', status: 'converted' },
    { id: 5, student: 'Anil Karki', destination: 'UK', course: 'Law', counsellor: 'Anita Maharjan', consultancy: 'Visa Pro', date: '2024-12-08', status: 'contacted' },
  ],
}
