export const countries = [
  { name: 'Australia', flag: '🇦🇺', code: 'au', counsellors: 24, image: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&q=80', desc: 'World class universities, post study work rights' },
  { name: 'Canada', flag: '🇨🇦', code: 'ca', counsellors: 31, image: 'https://images.unsplash.com/photo-1517935706615-2717063c2225?w=800&q=80', desc: 'PR friendly, affordable tuition, bilingual culture' },
  { name: 'United Kingdom', flag: '🇬🇧', code: 'gb', counsellors: 18, image: 'https://images.unsplash.com/photo-1513635269975-59663e0ac1ad?w=800&q=80', desc: 'Historic universities, 2 year post study visa' },
  { name: 'USA', flag: '🇺🇸', code: 'us', counsellors: 27, image: 'https://images.unsplash.com/photo-1485738422979-f5c462d49f74?w=800&q=80', desc: 'Top ranked universities, OPT work opportunities' },
  { name: 'Japan', flag: '🇯🇵', code: 'jp', counsellors: 12, image: 'https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?w=800&q=80', desc: 'Safe, affordable, scholarships available' },
  { name: 'Germany', flag: '🇩🇪', code: 'de', counsellors: 9, image: 'https://images.unsplash.com/photo-1467269204594-9661b134dd2b?w=800&q=80', desc: 'Free tuition at public universities, strong engineering' },
  { name: 'New Zealand', flag: '🇳🇿', code: 'nz', counsellors: 15, image: 'https://images.unsplash.com/photo-1507699622108-4be3abd695ad?w=800&q=80', desc: 'Safe, scenic, open work visa for partners' },
  { name: 'South Korea', flag: '🇰🇷', code: 'kr', counsellors: 8, image: 'https://images.unsplash.com/photo-1601621915196-2621bfb0cd6e?w=800&q=80', desc: 'Government scholarships, tech hub, affordable' },
]

export const consultancies = [
  { id: 1, name: 'Global Reach Education', logo: 'GR', location: 'Thamel, Kathmandu', phone: '+977 01-4XXXXXX', email: 'info@globalreach.com.np', counsellors: 8, rating: 4.8, reviews: 142, students: 520, established: 2015, featured: true, heroBanner: true, countries: ['Australia', 'Canada', 'UK'], tagline: 'Your gateway to world-class education', color: '#2563EB', verified: true, about: 'Global Reach Education has been helping Nepali students achieve their international education dreams since 2015. We have successfully placed over 500 students in top universities across Australia, Canada and UK.' },
  { id: 2, name: 'EduPath Consultancy', logo: 'EP', location: 'Lakeside, Pokhara', phone: '+977 061-XXXXXX', email: 'info@edupath.com.np', counsellors: 5, rating: 4.6, reviews: 98, students: 310, established: 2017, featured: true, heroBanner: true, countries: ['USA', 'Canada', 'Australia'], tagline: 'Charting your future, one visa at a time', color: '#06B6D4', verified: true, about: 'EduPath Consultancy specializes in USA and Canada admissions with a strong track record of scholarship placements. Our team of 5 expert counsellors guide you from selection to visa.' },
  { id: 3, name: 'Abroad Dreams Nepal', logo: 'AD', location: 'New Baneshwor, Kathmandu', phone: '+977 01-5XXXXXX', email: 'hello@abroadreams.com.np', counsellors: 6, rating: 4.7, reviews: 115, students: 280, established: 2018, featured: true, heroBanner: true, countries: ['Japan', 'South Korea', 'Germany'], tagline: 'Making your abroad dreams a reality', color: '#7C3AED', verified: true, about: 'Abroad Dreams Nepal is the leading consultancy for Asian destinations. We specialize in Japan language schools, Korean universities and German engineering programs.' },
  { id: 4, name: 'Visa Pro Nepal', logo: 'VP', location: 'Pulchowk, Lalitpur', phone: '+977 01-6XXXXXX', email: 'info@visapro.com.np', counsellors: 4, rating: 4.5, reviews: 76, students: 198, established: 2016, featured: false, heroBanner: false, countries: ['UK', 'Germany', 'New Zealand'], tagline: 'Expert visa guidance since 2016', color: '#059669', verified: true, about: 'Visa Pro Nepal has a 96% visa success rate with deep expertise in UK, Germany and New Zealand applications.' },
  { id: 5, name: 'Future Scholars', logo: 'FS', location: 'Bhaktapur', phone: '+977 01-7XXXXXX', email: 'info@futurescholars.com.np', counsellors: 3, rating: 4.4, reviews: 54, students: 120, established: 2020, featured: false, heroBanner: false, countries: ['Australia', 'New Zealand'], tagline: 'Scholarships and admissions made easy', color: '#DC2626', verified: false, about: 'Future Scholars focuses on scholarship-based admissions in Australia and New Zealand.' },
]

export const counsellors = [
  { id: 1, name: 'Priya Sharma', photo: 'https://randomuser.me/api/portraits/women/32.jpg', consultancy: 'Global Reach Education', consultancyId: 1, countries: ['Australia', 'Canada'], experience: 6, languages: ['Nepali', 'English', 'Hindi'], rating: 4.9, reviews: 67, students: 234, whatsapp: '9779841234567', bio: 'Specialized in Australian university admissions with 6 years of experience.', verified: true },
  { id: 2, name: 'Rohan Thapa', photo: 'https://randomuser.me/api/portraits/men/45.jpg', consultancy: 'Global Reach Education', consultancyId: 1, countries: ['UK', 'Canada'], experience: 4, languages: ['Nepali', 'English'], rating: 4.7, reviews: 45, students: 178, whatsapp: '9779841234568', bio: 'UK student visa specialist with strong relationships with Russell Group universities.', verified: true },
  { id: 3, name: 'Sita Gurung', photo: 'https://randomuser.me/api/portraits/women/68.jpg', consultancy: 'EduPath Consultancy', consultancyId: 2, countries: ['USA', 'Canada'], experience: 8, languages: ['Nepali', 'English', 'Newari'], rating: 4.8, reviews: 89, students: 312, whatsapp: '9779841234569', bio: 'IELTS certified counsellor with expertise in US university applications.', verified: true },
  { id: 4, name: 'Bikash Rai', photo: 'https://randomuser.me/api/portraits/men/22.jpg', consultancy: 'Abroad Dreams Nepal', consultancyId: 3, countries: ['Japan', 'South Korea'], experience: 5, languages: ['Nepali', 'English', 'Japanese'], rating: 4.9, reviews: 52, students: 189, whatsapp: '9779841234570', bio: 'Japan language school and university specialist. JLPT N2 certified.', verified: true },
  { id: 5, name: 'Anita Maharjan', photo: 'https://randomuser.me/api/portraits/women/44.jpg', consultancy: 'Visa Pro Nepal', consultancyId: 4, countries: ['UK', 'Germany'], experience: 7, languages: ['Nepali', 'English', 'German'], rating: 4.6, reviews: 38, students: 156, whatsapp: '9779841234571', bio: 'German university admissions expert.', verified: true },
  { id: 6, name: 'Suraj Pandey', photo: 'https://randomuser.me/api/portraits/men/56.jpg', consultancy: 'Future Scholars', consultancyId: 5, countries: ['Australia', 'New Zealand'], experience: 3, languages: ['Nepali', 'English'], rating: 4.5, reviews: 29, students: 97, whatsapp: '9779841234572', bio: 'Young and passionate counsellor focused on scholarship opportunities.', verified: false },
]

export const successStories = [
  { id: 1, name: 'Aarav KC', university: 'University of Melbourne', country: 'Australia', course: 'MBA', year: 2024, consultancy: 'Global Reach Education', consultancyId: 1, counsellor: 'Priya Sharma', type: 'video', video: 'https://www.w3schools.com/html/mov_bbb.mp4', thumbnail: 'https://images.unsplash.com/photo-1523050854058-8df90110c9f1?w=800&q=80', quote: 'Got into my dream university with full scholarship. CounselNepal made it possible! The process was smooth and my counsellor guided me every step of the way.' },
  { id: 2, name: 'Manisha Tamang', university: 'University of Toronto', country: 'Canada', course: 'Computer Science', year: 2024, consultancy: 'EduPath Consultancy', consultancyId: 2, counsellor: 'Sita Gurung', type: 'video', video: 'https://www.w3schools.com/html/movie.mp4', thumbnail: 'https://images.unsplash.com/photo-1541339907198-e08756dedf3f?w=800&q=80', quote: 'The counsellor helped me get a $15,000 scholarship. Best decision I ever made.' },
  { id: 3, name: 'Dipesh Shrestha', university: 'Waseda University', country: 'Japan', course: 'Engineering', year: 2023, consultancy: 'Abroad Dreams Nepal', consultancyId: 3, counsellor: 'Bikash Rai', type: 'video', video: 'https://www.w3schools.com/html/mov_bbb.mp4', thumbnail: 'https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?w=800&q=80', quote: 'Now studying in Tokyo! The Japanese language support from Bikash was invaluable.' },
  { id: 4, name: 'Sunita Karki', university: 'University of Leeds', country: 'UK', course: 'Public Health', year: 2024, consultancy: 'Global Reach Education', consultancyId: 1, counsellor: 'Rohan Thapa', type: 'text', video: null, thumbnail: 'https://randomuser.me/api/portraits/women/55.jpg', quote: 'Rohan helped me with my SOP and scholarship application. I got a partial scholarship at Leeds. The entire visa process was handled professionally. I would highly recommend Global Reach to anyone planning to study in the UK.' },
  { id: 5, name: 'Ramesh Adhikari', university: 'TU Dortmund', country: 'Germany', course: 'Mechanical Engineering', year: 2023, consultancy: 'Visa Pro Nepal', consultancyId: 4, counsellor: 'Anita Maharjan', type: 'text', video: null, thumbnail: 'https://randomuser.me/api/portraits/men/67.jpg', quote: 'Studying in Germany for free was my dream. Anita guided me through the APS certificate, blocked account and everything. She replied to my every query patiently. Now in my second semester at TU Dortmund!' },
  { id: 6, name: 'Puja Thapa', university: 'Kyoto University', country: 'Japan', course: 'Language & Culture', year: 2024, consultancy: 'Abroad Dreams Nepal', consultancyId: 3, counsellor: 'Bikash Rai', type: 'text', video: null, thumbnail: 'https://randomuser.me/api/portraits/women/29.jpg', quote: 'I had zero knowledge about Japan admission process. Bikash handled everything from language school selection to COE application. Within 8 months I was in Kyoto. Abroad Dreams Nepal is the best for Japan!' },
]

export const events = [
  { id: 1, title: 'Australia University Fair 2025', consultancy: 'Global Reach Education', consultancyId: 1, date: '2025-04-15', time: '10:00 AM - 4:00 PM', location: 'Hotel Annapurna, Kathmandu', type: 'Fair', image: 'https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=800&q=80', description: 'Meet representatives from 20+ Australian universities. Free IELTS consultation on the spot. Bring your academic documents for instant assessment.', seats: 200, registered: 145, color: '#2563EB', free: true },
  { id: 2, title: 'Canada PR Pathway Seminar', consultancy: 'EduPath Consultancy', consultancyId: 2, date: '2025-04-20', time: '2:00 PM - 5:00 PM', location: 'Pokhara Grand Hotel', type: 'Seminar', image: 'https://images.unsplash.com/photo-1475721027785-f74eccf877e2?w=800&q=80', description: 'Learn about Canada PR pathways after study. Express Entry, PNP streams explained in detail by immigration experts.', seats: 100, registered: 67, color: '#06B6D4', free: true },
  { id: 3, title: 'Japan Language School Open Day', consultancy: 'Abroad Dreams Nepal', consultancyId: 3, date: '2025-04-25', time: '11:00 AM - 3:00 PM', location: 'New Baneshwor, Kathmandu', type: 'Open Day', image: 'https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?w=800&q=80', description: 'Connect with Japan language school representatives. Free Japanese language demo class. Scholarship opportunities discussed.', seats: 80, registered: 52, color: '#7C3AED', free: true },
  { id: 4, title: 'UK University Scholarship Workshop', consultancy: 'Visa Pro Nepal', consultancyId: 4, date: '2025-05-02', time: '10:00 AM - 1:00 PM', location: 'Pulchowk, Lalitpur', type: 'Workshop', image: 'https://images.unsplash.com/photo-1513635269975-59663e0ac1ad?w=800&q=80', description: 'Chevening and Commonwealth scholarship application guidance. SOP writing tips from successful alumni.', seats: 60, registered: 38, color: '#059669', free: false },
  { id: 5, title: 'Study Abroad Expo 2025', consultancy: 'Global Reach Education', consultancyId: 1, date: '2025-05-10', time: '9:00 AM - 6:00 PM', location: 'Bhrikutimandap, Kathmandu', type: 'Expo', image: 'https://images.unsplash.com/photo-1431540015161-0bf868a2d407?w=800&q=80', description: 'Nepal biggest study abroad expo. 30+ consultancies, 50+ universities, on-spot admission offers.', seats: 1000, registered: 678, color: '#2563EB', free: true },
  { id: 6, title: 'Germany Free Education Webinar', consultancy: 'Visa Pro Nepal', consultancyId: 4, date: '2025-05-18', time: '6:00 PM - 8:00 PM', location: 'Online (Zoom)', type: 'Webinar', image: 'https://images.unsplash.com/photo-1467269204594-9661b134dd2b?w=800&q=80', description: 'How to study in Germany for free. Application process, blocked account, APS certificate explained step by step.', seats: 500, registered: 201, color: '#059669', free: true },
]

export const reviews = [
  { id: 1, student: 'Aarav K.', counsellor: 'Priya Sharma', country: 'Australia', university: 'University of Melbourne', rating: 5, text: 'Priya was incredibly helpful throughout my application process. Got into my dream university!', willVisit: true, wasHelpful: true, date: '2024-11-15' },
  { id: 2, student: 'Manisha T.', counsellor: 'Sita Gurung', country: 'USA', university: 'University of Texas', rating: 5, text: 'The entire process from application to visa was smooth. Highly recommend EduPath.', willVisit: true, wasHelpful: true, date: '2024-10-22' },
  { id: 3, student: 'Dipesh B.', counsellor: 'Bikash Rai', country: 'Japan', university: 'Waseda University', rating: 5, text: 'Bikash helped me with my Japanese language school application. Now studying in Tokyo!', willVisit: true, wasHelpful: true, date: '2024-12-01' },
]

export const analytics = {
  totalVisitors: 12847, totalLogins: 4231, totalLeads: 1876, totalWhatsappClicks: 1543, conversionRate: 36.4,
  topCountries: [{ country: 'Australia', leads: 524 }, { country: 'Canada', leads: 412 }, { country: 'USA', leads: 387 }, { country: 'UK', leads: 298 }, { country: 'Japan', leads: 255 }],
  leadsPerConsultancy: [{ name: 'Global Reach', leads: 487 }, { name: 'EduPath', leads: 398 }, { name: 'Abroad Dreams', leads: 312 }, { name: 'Visa Pro', leads: 234 }, { name: 'Future Scholars', leads: 145 }],
  recentLeads: [
    { id: 1, student: 'Ram Prasad', destination: 'Australia', course: 'MBA', counsellor: 'Priya Sharma', consultancy: 'Global Reach', date: '2024-12-10', status: 'new' },
    { id: 2, student: 'Srijana KC', destination: 'Canada', course: 'Computer Science', counsellor: 'Rohan Thapa', consultancy: 'Global Reach', date: '2024-12-10', status: 'contacted' },
    { id: 3, student: 'Niraj Shrestha', destination: 'USA', course: 'Engineering', counsellor: 'Sita Gurung', consultancy: 'EduPath', date: '2024-12-09', status: 'new' },
    { id: 4, student: 'Puja Tamang', destination: 'Japan', course: 'Language Course', counsellor: 'Bikash Rai', consultancy: 'Abroad Dreams', date: '2024-12-09', status: 'converted' },
    { id: 5, student: 'Anil Karki', destination: 'UK', course: 'Law', counsellor: 'Anita Maharjan', consultancy: 'Visa Pro', date: '2024-12-08', status: 'contacted' },
  ],
}

export const promoTopics = [
  { id: 'purpose', label: 'Purpose Clear गर्नु', icon: '🎯' },
  { id: 'country', label: 'Country छनोट', icon: '🌍' },
  { id: 'course', label: 'Course / Job Selection', icon: '🎓' },
  { id: 'documentation', label: 'Documentation', icon: '📄' },
  { id: 'language', label: 'Language Requirement', icon: '🗣️' },
  { id: 'visa', label: 'Visa Risk बुझ्नु', icon: '⚠️' },
  { id: 'mistakes', label: 'Common Mistakes', icon: '🚫' },
  { id: 'ielts-free', label: 'IELTS बिना कहाँ जान', icon: '📝' },
  { id: 'low-budget', label: 'Low Budget देशहरू', icon: '💰' },
]

export const promos = [
  { id: 1, title: 'Australia मा IELTS बिना जान सकिन्छ?', topic: 'ielts-free', topicLabel: 'IELTS बिना कहाँ जान', consultancy: 'Global Reach Education', consultancyId: 1, consultancyColor: '#2563EB', consultancyLogo: 'GR', author: 'Priya Sharma', date: '2025-03-10', readTime: '3 min', thumbnail: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&q=80', summary: 'धेरै students सोच्छन् कि Australia जान IELTS अनिवार्य छ। तर केही pathways मा IELTS बिना पनि जान सकिन्छ।', content: `## Australia मा IELTS बिना जान सकिन्छ?\n\nधेरै Nepali students को मनमा यो प्रश्न आउँछ — के IELTS नगरी Australia जान मिल्छ?\n\n### हो, केही cases मा मिल्छ:\n\n**1. Institutional IELTS Waiver**\nकेही Australian universities ले आफ्नै English test लिन्छन्। तिनीहरूले IELTS को सट्टा आफ्नो internal test accept गर्छन्।\n\n**2. Previous English Medium Education**\nयदि तपाईंले SLC/SEE देखि +2 सम्म English medium मा पढ्नु भएको छ भने, केही universities ले IELTS माफ गर्न सक्छन्।\n\n**3. Foundation Programs**\nकेही foundation programs मा IELTS requirement कम हुन्छ — 5.5 सम्म।\n\n### तर याद राख्नु:\n- Student visa को लागि DHA (Department of Home Affairs) ले minimum English requirement माग्छ\n- IELTS 6.0 overall (with no band below 5.5) standard requirement हो\n- IELTS भएको students को visa approval rate धेरै राम्रो हुन्छ\n\n### हाम्रो सुझाव:\nIELTS को तयारी गर्नु नै best approach हो। हाम्रो consultancy मा free IELTS counselling available छ।`, status: 'live', views: 342, likes: 28 },
  { id: 2, title: 'Canada PR को लागि कुन course राम्रो?', topic: 'course', topicLabel: 'Course / Job Selection', consultancy: 'EduPath Consultancy', consultancyId: 2, consultancyColor: '#06B6D4', consultancyLogo: 'EP', author: 'Sita Gurung', date: '2025-03-08', readTime: '4 min', thumbnail: 'https://images.unsplash.com/photo-1517935706615-2717063c2225?w=800&q=80', summary: 'Canada मा पढेर PR लिने plan छ? भने course selection नै सबभन्दा important step हो। गलत course = PR को chance कम।', content: `## Canada PR को लागि कुन course राम्रो?\n\nCanada मा study गरेर PR लिने Nepali students को dream हुन्छ। तर सबै courses PR को लागि equally helpful हुँदैनन्।\n\n### PR-friendly courses:\n\n**1. Information Technology (IT)**\n- Software Developer, Data Analyst, Cybersecurity\n- NOC codes: 21231, 21220\n- Job market: Excellent\n- Average salary: CAD 70,000+\n\n**2. Healthcare**\n- Nursing, Pharmacy, Medical Lab\n- Always in demand across all provinces\n- Fast track PR through PNP programs\n\n**3. Trades**\n- Electrician, Plumber, Welder\n- Red Seal certification = PR advantage\n- High demand, less competition\n\n**4. Business & Management**\n- MBA, Supply Chain, Project Management\n- Good for experienced professionals\n\n### Avoid these mistakes:\n- Arts/Humanities courses — PR path difficult\n- Courses with no Canadian job market\n- Programs not recognized by IRCC\n\n### Bottom line:\nIT र Healthcare नै currently best PR pathway हो Canada मा।`, status: 'live', views: 518, likes: 45 },
  { id: 3, title: 'Japan Visa Reject हुने 5 कारण', topic: 'visa', topicLabel: 'Visa Risk बुझ्नु', consultancy: 'Abroad Dreams Nepal', consultancyId: 3, consultancyColor: '#7C3AED', consultancyLogo: 'AD', author: 'Bikash Rai', date: '2025-03-05', readTime: '3 min', thumbnail: 'https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?w=800&q=80', summary: 'Japan student visa reject हुनु common छ। तर यी 5 कारण थाहा भयो भने तपाईंको visa approve हुने chance धेरै बढ्छ।', content: `## Japan Visa Reject हुने 5 Main कारण\n\n### 1. Weak Motivation Letter\nJapan embassy ले motivation letter लाई धेरै seriously लिन्छ। "I want to learn Japanese culture" जस्तो generic letter ले काम गर्दैन। Specific goals चाहिन्छ।\n\n### 2. Low Bank Balance\nJapan visa को लागि minimum 5-7 lakh NPR bank statement चाहिन्छ। Last 6 months को consistent balance देखाउनु पर्छ। Sudden deposit = suspicious.\n\n### 3. Gap in Education\nEducation gap छ भने proper explanation letter चाहिन्छ। Gap को reason convincing हुनु पर्छ।\n\n### 4. Previous Visa Rejection\nअरू country को visa reject भएको छ भने Japan embassy लाई honestly बताउनु पर्छ। Hide गर्नु = automatic rejection.\n\n### 5. Incomplete Documents\nMissing documents नै सबभन्दा common rejection reason हो। Checklist:\n- Acceptance letter\n- Financial guarantee\n- Academic transcripts\n- Certificate of eligibility (COE)\n\n### हाम्रो success rate:\nAbroad Dreams Nepal को Japan visa success rate 94% छ last 2 years मा।`, status: 'live', views: 621, likes: 67 },
  { id: 4, title: 'Germany मा Free मा पढ्ने पूरा guide', topic: 'low-budget', topicLabel: 'Low Budget देशहरू', consultancy: 'Visa Pro Nepal', consultancyId: 4, consultancyColor: '#059669', consultancyLogo: 'VP', author: 'Anita Maharjan', date: '2025-03-01', readTime: '5 min', thumbnail: 'https://images.unsplash.com/photo-1467269204594-9661b134dd2b?w=800&q=80', summary: 'Germany मा public universities मा tuition fee नै छैन। Low budget मा Europe को top education लिन सकिन्छ। यहाँ पूरा process छ।', content: `## Germany मा Free Education — Complete Guide\n\n### किन Germany?\n- Public universities मा NO tuition fee\n- Semester contribution only: ~€350/semester\n- Living cost: €800-1000/month\n- Strong engineering & technical programs\n- 18 month job seeker visa after graduation\n\n### Requirements:\n\n**Academic:**\n- Bachelor's degree with good GPA\n- APS Certificate (Academic Evaluation Centre) — mandatory for Nepali students\n- Takes 6-8 weeks, costs €200\n\n**Language:**\n- German taught programs: B2/C1 German\n- English taught programs: IELTS 6.5 / TOEFL 90\n\n**Financial:**\n- Blocked account: €11,208 (for 1 year)\n- This money is yours — you withdraw monthly\n\n### Application Process:\n1. Get APS Certificate\n2. Choose university on uni-assist.de\n3. Apply directly or through uni-assist\n4. Get admission letter\n5. Open blocked account (Deutsche Bank / Fintiba)\n6. Apply for student visa at German embassy Kathmandu\n\n### Timeline:\n- Start preparation: 12-18 months before intake\n- Winter intake: October (apply by May-June)\n- Summer intake: April (apply by November)\n\n### Popular universities for Nepali students:\n- TU Munich, TU Berlin, RWTH Aachen (Engineering)\n- Heidelberg, LMU Munich (Sciences)\n- FU Berlin (Social Sciences)`, status: 'live', views: 892, likes: 103 },
  { id: 5, title: 'SOP कसरी लेख्ने — Complete Guide', topic: 'documentation', topicLabel: 'Documentation', consultancy: 'Global Reach Education', consultancyId: 1, consultancyColor: '#2563EB', consultancyLogo: 'GR', author: 'Rohan Thapa', date: '2025-02-28', readTime: '4 min', thumbnail: 'https://images.unsplash.com/photo-1455390582262-044cdead277a?w=800&q=80', summary: 'Statement of Purpose (SOP) नै visa को सबभन्दा important document हो। राम्रो SOP = visa approve। यसरी लेख्नु होस्।', content: `## SOP कसरी लेख्ने — Step by Step Guide\n\nSOP (Statement of Purpose) तपाईंको visa application को heart हो। Embassy officer ले यो document पढेर decide गर्छन् — तपाईं genuine student हौ कि होइन।\n\n### SOP Structure:\n\n**Paragraph 1: Introduction**\nआफ्नो background — academic qualification, work experience (if any)\n\n**Paragraph 2: Why this course?**\nCourse choose गर्नुको specific reason। Future career connection देखाउनु।\n\n**Paragraph 3: Why this country/university?**\nGeneric नलेख्नु। Specific — "University of Melbourne को Business School Forbes मा Top 50 मा छ र Professor X को research मसँग match गर्छ।"\n\n**Paragraph 4: Financial situation**\nKasle sponsor गर्दैछ? Funds कहाँबाट आउँछ? Clearly explain गर्नु।\n\n**Paragraph 5: Future plans**\nMost important — study पछि के गर्ने? Nepal फर्कने plan छ भने clearly भन्नु। Ties to home country देखाउनु।\n\n### Common mistakes:\n- Copy paste गर्नु — embassy detect गर्छ\n- Too long (> 1.5 pages)\n- Emotional language\n- Spelling/grammar errors\n- Vague future plans\n\n### Pro tip:\nSOP आफैंले लेख्नु। Consultancy ले help गर्न सक्छ तर आफ्नो voice राख्नु।`, status: 'live', views: 445, likes: 52 },
  { id: 6, title: 'UK Student Visa Documents Checklist 2025', topic: 'documentation', topicLabel: 'Documentation', consultancy: 'Visa Pro Nepal', consultancyId: 4, consultancyColor: '#059669', consultancyLogo: 'VP', author: 'Anita Maharjan', date: '2025-02-25', readTime: '3 min', thumbnail: 'https://images.unsplash.com/photo-1513635269975-59663e0ac1ad?w=800&q=80', summary: 'UK Student visa (Tier 4) को लागि exactly के के documents चाहिन्छ? 2025 updated checklist यहाँ छ।', content: `## UK Student Visa Documents Checklist 2025\n\n### Mandatory Documents:\n\n**From University:**\n- CAS (Confirmation of Acceptance for Studies) number\n- Unconditional offer letter\n\n**Identity:**\n- Valid passport (6+ months validity)\n- Passport size photos (white background)\n\n**Financial:**\n- Bank statement (28 consecutive days)\n- Minimum £1,334/month for London, £1,023/month outside London\n- Sponsorship letter if parents sponsoring\n\n**Academic:**\n- All academic certificates and transcripts\n- IELTS certificate (minimum 6.0 overall)\n\n**Other:**\n- ATAS certificate (if required for your course)\n- TB test result from IOM Kathmandu\n- Previous UK visa (if any)\n\n### Important points:\n- Apply online at gov.uk/student-visa\n- Biometric appointment at VFS Global Kathmandu\n- Processing time: 3 weeks standard, 1 week priority\n- Visa fee: £490 + Immigration Health Surcharge (£776/year)\n\n### Our tip:\nBank statement 28 days consistently maintain गर्नु। Last minute deposit नगर्नु।`, status: 'live', views: 334, likes: 41 },
]

export const universities = [
  // AUSTRALIA
  { id: 1, name: 'University of Melbourne', country: 'Australia', flag: '🇦🇺', ranking: 33, image: 'https://images.unsplash.com/photo-1523050854058-8df90110c9f1?w=800&q=80', location: 'Melbourne, Victoria', type: 'Public', established: 1853, tuitionMin: 38000, tuitionMax: 46000, currency: 'AUD', ieltsMin: 6.5, ieltsOverall: 7.0, deadlines: ['March 31 (Semester 2)', 'October 31 (Semester 1)'], scholarship: true, scholarshipName: 'Melbourne International Undergraduate Scholarship', scholarshipAmount: 'Up to AUD 10,000', popularCourses: ['MBA', 'Computer Science', 'Medicine', 'Law', 'Engineering'], website: 'unimelb.edu.au', about: 'Australia\'s leading university and one of the world\'s top 50. Known for research excellence and diverse student community.' },
  { id: 2, name: 'Monash University', country: 'Australia', flag: '🇦🇺', ranking: 57, image: 'https://images.unsplash.com/photo-1541339907198-e08756dedf3f?w=800&q=80', location: 'Melbourne, Victoria', type: 'Public', established: 1958, tuitionMin: 34000, tuitionMax: 42000, currency: 'AUD', ieltsMin: 6.0, ieltsOverall: 6.5, deadlines: ['April 30 (Semester 2)', 'November 30 (Semester 1)'], scholarship: true, scholarshipName: 'Monash International Merit Scholarship', scholarshipAmount: 'AUD 5,000 - 10,000', popularCourses: ['Engineering', 'Pharmacy', 'Business', 'IT', 'Education'], website: 'monash.edu', about: 'A member of the prestigious Group of Eight, Monash is known for its strong industry connections and global campuses.' },
  { id: 3, name: 'University of Sydney', country: 'Australia', flag: '🇦🇺', ranking: 41, image: 'https://images.unsplash.com/photo-1607237138185-eedd9c632b0b?w=800&q=80', location: 'Sydney, NSW', type: 'Public', established: 1850, tuitionMin: 36000, tuitionMax: 48000, currency: 'AUD', ieltsMin: 6.5, ieltsOverall: 7.0, deadlines: ['March 31', 'September 30'], scholarship: true, scholarshipName: 'International Excellence Award', scholarshipAmount: 'AUD 5,000', popularCourses: ['Medicine', 'Law', 'Architecture', 'Business', 'Engineering'], website: 'sydney.edu.au', about: 'Australia\'s first university, consistently ranked among the world\'s best. Beautiful sandstone campus in the heart of Sydney.' },

  // CANADA
  { id: 4, name: 'University of Toronto', country: 'Canada', flag: '🇨🇦', ranking: 21, image: 'https://images.unsplash.com/photo-1569523420547-b8ac5ce77543?w=800&q=80', location: 'Toronto, Ontario', type: 'Public', established: 1827, tuitionMin: 45000, tuitionMax: 68000, currency: 'CAD', ieltsMin: 6.5, ieltsOverall: 7.0, deadlines: ['January 15 (Fall)', 'September 15 (Winter)'], scholarship: true, scholarshipName: 'Lester B. Pearson Scholarship', scholarshipAmount: 'Full tuition + living', popularCourses: ['Computer Science', 'Engineering', 'Medicine', 'Business', 'Law'], website: 'utoronto.ca', about: 'Canada\'s top university and one of the world\'s most innovative research universities. Located in one of the world\'s most multicultural cities.' },
  { id: 5, name: 'University of British Columbia', country: 'Canada', flag: '🇨🇦', ranking: 38, image: 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=800&q=80', location: 'Vancouver, BC', type: 'Public', established: 1908, tuitionMin: 38000, tuitionMax: 55000, currency: 'CAD', ieltsMin: 6.5, ieltsOverall: 6.5, deadlines: ['January 15 (September intake)', 'September 15 (January intake)'], scholarship: true, scholarshipName: 'International Leader of Tomorrow Award', scholarshipAmount: 'Partial to full tuition', popularCourses: ['Engineering', 'Forestry', 'Sciences', 'MBA', 'Film'], website: 'ubc.ca', about: 'Consistently ranked among the top 40 universities globally. Stunning campus between mountains and ocean in Vancouver.' },
  { id: 6, name: 'McGill University', country: 'Canada', flag: '🇨🇦', ranking: 46, image: 'https://images.unsplash.com/photo-1562774053-701939374585?w=800&q=80', location: 'Montreal, Quebec', type: 'Public', established: 1821, tuitionMin: 28000, tuitionMax: 45000, currency: 'CAD', ieltsMin: 6.5, ieltsOverall: 7.0, deadlines: ['January 15 (Fall)', 'September 1 (Winter)'], scholarship: true, scholarshipName: 'McGill Entrance Scholarship', scholarshipAmount: 'CAD 3,000 - 12,000', popularCourses: ['Medicine', 'Law', 'Engineering', 'Music', 'Science'], website: 'mcgill.ca', about: 'Known as the Harvard of Canada. Bilingual city, lower cost of living than Toronto. Strong medical and law programs.' },

  // UK
  { id: 7, name: 'University of Oxford', country: 'United Kingdom', flag: '🇬🇧', ranking: 1, image: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=800&q=80', location: 'Oxford, England', type: 'Public', established: 1096, tuitionMin: 28950, tuitionMax: 39010, currency: 'GBP', ieltsMin: 7.0, ieltsOverall: 7.5, deadlines: ['October 15 (most courses)', 'January 15 (some courses)'], scholarship: true, scholarshipName: 'Rhodes Scholarship', scholarshipAmount: 'Full funding', popularCourses: ['PPE', 'Medicine', 'Law', 'Computer Science', 'History'], website: 'ox.ac.uk', about: 'The world\'s oldest English-speaking university. Exceptional tutorial system, world-leading research, iconic collegiate structure.' },
  { id: 8, name: 'University of Manchester', country: 'United Kingdom', flag: '🇬🇧', ranking: 28, image: 'https://images.unsplash.com/photo-1529655683826-aba9b3e77383?w=800&q=80', location: 'Manchester, England', type: 'Public', established: 1824, tuitionMin: 22000, tuitionMax: 32000, currency: 'GBP', ieltsMin: 6.0, ieltsOverall: 6.5, deadlines: ['January 31 (September)', 'October 31 (January)'], scholarship: true, scholarshipName: 'President\'s Doctoral Scholar Award', scholarshipAmount: 'Full tuition + stipend', popularCourses: ['Business', 'Engineering', 'Computer Science', 'Life Sciences', 'Architecture'], website: 'manchester.ac.uk', about: 'Russell Group university with 25 Nobel laureates. Affordable city with vibrant student life. Popular destination for Nepali students.' },

  // USA
  { id: 9, name: 'Massachusetts Institute of Technology', country: 'USA', flag: '🇺🇸', ranking: 1, image: 'https://images.unsplash.com/photo-1564981797816-1043664bf78d?w=800&q=80', location: 'Cambridge, Massachusetts', type: 'Private', established: 1861, tuitionMin: 57986, tuitionMax: 57986, currency: 'USD', ieltsMin: 7.0, ieltsOverall: 7.5, deadlines: ['January 1 (Regular Decision)', 'November 1 (Early Action)'], scholarship: true, scholarshipName: 'MIT Need-Based Aid', scholarshipAmount: 'Meets 100% of demonstrated need', popularCourses: ['Computer Science', 'Engineering', 'Physics', 'Architecture', 'Economics'], website: 'mit.edu', about: 'The world\'s leading science and technology institution. Need-blind admissions for international students. Exceptional research opportunities.' },
  { id: 10, name: 'University of Texas at Austin', country: 'USA', flag: '🇺🇸', ranking: 67, image: 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=800&q=80', location: 'Austin, Texas', type: 'Public', established: 1883, tuitionMin: 38000, tuitionMax: 45000, currency: 'USD', ieltsMin: 6.5, ieltsOverall: 7.0, deadlines: ['December 1 (Fall)', 'September 1 (Spring)'], scholarship: true, scholarshipName: 'International Distinction Award', scholarshipAmount: 'USD 5,000/year', popularCourses: ['Engineering', 'Business', 'Computer Science', 'Film', 'Law'], website: 'utexas.edu', about: 'One of the largest universities in the US. Located in the tech hub of Austin. Strong engineering and business programs.' },

  // JAPAN
  { id: 11, name: 'Waseda University', country: 'Japan', flag: '🇯🇵', ranking: 201, image: 'https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?w=800&q=80', location: 'Tokyo', type: 'Private', established: 1882, tuitionMin: 1200000, tuitionMax: 1800000, currency: 'JPY', ieltsMin: 6.0, ieltsOverall: 6.5, deadlines: ['November (April intake)', 'May (September intake)'], scholarship: true, scholarshipName: 'Waseda University Scholarship', scholarshipAmount: 'Full or partial tuition', popularCourses: ['International Relations', 'Business', 'Engineering', 'Political Science', 'Japanese Studies'], website: 'waseda.jp', about: 'One of Japan\'s most prestigious private universities. Strong English programs. Located in the heart of Tokyo.' },
  { id: 12, name: 'Kyoto University', country: 'Japan', flag: '🇯🇵', ranking: 68, image: 'https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=800&q=80', location: 'Kyoto', type: 'Public', established: 1897, tuitionMin: 535800, tuitionMax: 535800, currency: 'JPY', ieltsMin: 6.5, ieltsOverall: 6.5, deadlines: ['February (October intake)', 'August (April intake)'], scholarship: true, scholarshipName: 'MEXT Government Scholarship', scholarshipAmount: 'Full tuition + monthly allowance', popularCourses: ['Science', 'Engineering', 'Medicine', 'Agriculture', 'Liberal Arts'], website: 'kyoto-u.ac.jp', about: 'Japan\'s second most prestigious national university. Known for sciences and research. Beautiful historic city of Kyoto.' },

  // GERMANY
  { id: 13, name: 'Technical University of Munich', country: 'Germany', flag: '🇩🇪', ranking: 37, image: 'https://images.unsplash.com/photo-1467269204594-9661b134dd2b?w=800&q=80', location: 'Munich, Bavaria', type: 'Public', established: 1868, tuitionMin: 0, tuitionMax: 700, currency: 'EUR', ieltsMin: 0, ieltsOverall: 6.5, deadlines: ['May 31 (Winter/October)', 'November 30 (Summer/April)'], scholarship: true, scholarshipName: 'DAAD Scholarship', scholarshipAmount: '€861/month + travel allowance', popularCourses: ['Engineering', 'Computer Science', 'Natural Sciences', 'Business', 'Architecture'], website: 'tum.de', about: 'Germany\'s top technical university. No tuition fees for most programs. Strong industry partnerships with BMW, Siemens, Allianz.' },
  { id: 14, name: 'Heidelberg University', country: 'Germany', flag: '🇩🇪', ranking: 66, image: 'https://images.unsplash.com/photo-1467269204594-9661b134dd2b?w=800&q=80', location: 'Heidelberg, Baden-Württemberg', type: 'Public', established: 1386, tuitionMin: 0, tuitionMax: 700, currency: 'EUR', ieltsMin: 0, ieltsOverall: 6.5, deadlines: ['April 15 (Winter)', 'October 15 (Summer)'], scholarship: true, scholarshipName: 'Deutschlandstipendium', scholarshipAmount: '€300/month', popularCourses: ['Medicine', 'Natural Sciences', 'Law', 'Economics', 'Philosophy'], website: 'uni-heidelberg.de', about: 'Germany\'s oldest university, founded in 1386. Exceptional research environment. Located in a beautiful historic city.' },

  // NEW ZEALAND
  { id: 15, name: 'University of Auckland', country: 'New Zealand', flag: '🇳🇿', ranking: 87, image: 'https://images.unsplash.com/photo-1507699622108-4be3abd695ad?w=800&q=80', location: 'Auckland', type: 'Public', established: 1883, tuitionMin: 32000, tuitionMax: 42000, currency: 'NZD', ieltsMin: 6.0, ieltsOverall: 6.5, deadlines: ['December 1 (Semester 1)', 'July 1 (Semester 2)'], scholarship: true, scholarshipName: 'University of Auckland International Student Excellence Scholarship', scholarshipAmount: 'NZD 10,000', popularCourses: ['Engineering', 'Business', 'Law', 'Arts', 'Medical Science'], website: 'auckland.ac.nz', about: 'New Zealand\'s largest and highest ranked university. Safe, multicultural city. Post-study work visa available.' },

  // SOUTH KOREA
  { id: 16, name: 'Seoul National University', country: 'South Korea', flag: '🇰🇷', ranking: 36, image: 'https://images.unsplash.com/photo-1601621915196-2621bfb0cd6e?w=800&q=80', location: 'Seoul', type: 'Public', established: 1946, tuitionMin: 3000000, tuitionMax: 6000000, currency: 'KRW', ieltsMin: 0, ieltsOverall: 6.0, deadlines: ['September (Spring intake)', 'March (Fall intake)'], scholarship: true, scholarshipName: 'GKS (Korean Government Scholarship)', scholarshipAmount: 'Full tuition + monthly allowance', popularCourses: ['Engineering', 'Business', 'Medicine', 'Liberal Arts', 'Computer Science'], website: 'snu.ac.kr', about: 'South Korea\'s most prestigious university. Strong scholarship opportunities through GKS program. K-culture hub, affordable living.' },
]

export const extendedUniversities = [
  // AUSTRALIA
  { id: 101, name: 'University of Melbourne', country: 'Australia', flag: '🇦🇺', city: 'Melbourne', ranking: 33, image: 'https://images.unsplash.com/photo-1523050854058-8df90110c9f1?w=800&q=80', type: 'Public', established: 1853, tuitionMin: 38000, tuitionMax: 46000, currency: 'AUD', ieltsMin: 6.5, ieltsOverall: 7.0, scholarship: true, scholarshipName: 'Melbourne International Scholarship', scholarshipAmount: 'AUD 10,000', gpaMin: 3.0, intakes: ['Feb', 'Jul'], courses: ['MBA', 'Computer Science', 'Medicine', 'Law', 'Engineering', 'Psychology'], duration: '2–4 years', sopRequired: true, lorRequired: true, accommodationCost: 'AUD 800–1,500/mo', livingCost: 'AUD 1,800–2,500/mo', onCampus: true, partTimeHours: '48hrs/fortnight', postStudyVisa: '2–4 years', jobMarket: 'Very High', website: 'unimelb.edu.au', about: "Australia's leading university, consistently ranked top 50 globally. Strong research culture and diverse student community." },
  { id: 102, name: 'Monash University', country: 'Australia', flag: '🇦🇺', city: 'Melbourne', ranking: 57, image: 'https://images.unsplash.com/photo-1541339907198-e08756dedf3f?w=800&q=80', type: 'Public', established: 1958, tuitionMin: 34000, tuitionMax: 42000, currency: 'AUD', ieltsMin: 6.0, ieltsOverall: 6.5, scholarship: true, scholarshipName: 'Monash International Merit Scholarship', scholarshipAmount: 'AUD 5,000–10,000', gpaMin: 2.8, intakes: ['Feb', 'Jul'], courses: ['Engineering', 'Pharmacy', 'Business', 'IT', 'Education', 'Science'], duration: '2–4 years', sopRequired: true, lorRequired: false, accommodationCost: 'AUD 700–1,300/mo', livingCost: 'AUD 1,700–2,300/mo', onCampus: true, partTimeHours: '48hrs/fortnight', postStudyVisa: '2–4 years', jobMarket: 'High', website: 'monash.edu', about: 'Group of Eight member with strong industry connections and global campuses including Malaysia.' },
  { id: 103, name: 'University of Sydney', country: 'Australia', flag: '🇦🇺', city: 'Sydney', ranking: 41, image: 'https://images.unsplash.com/photo-1607237138185-eedd9c632b0b?w=800&q=80', type: 'Public', established: 1850, tuitionMin: 36000, tuitionMax: 48000, currency: 'AUD', ieltsMin: 6.5, ieltsOverall: 7.0, scholarship: true, scholarshipName: 'International Excellence Award', scholarshipAmount: 'AUD 5,000', gpaMin: 3.2, intakes: ['Feb', 'Aug'], courses: ['Medicine', 'Law', 'Architecture', 'Business', 'Engineering', 'Arts'], duration: '3–5 years', sopRequired: true, lorRequired: true, accommodationCost: 'AUD 900–1,600/mo', livingCost: 'AUD 2,000–2,800/mo', onCampus: true, partTimeHours: '48hrs/fortnight', postStudyVisa: '2–4 years', jobMarket: 'Very High', website: 'sydney.edu.au', about: "Australia's first university with iconic sandstone campus in the heart of Sydney." },
  { id: 104, name: 'University of Queensland', country: 'Australia', flag: '🇦🇺', city: 'Brisbane', ranking: 50, image: 'https://images.unsplash.com/photo-1523050854058-8df90110c9f1?w=800&q=80', type: 'Public', established: 1909, tuitionMin: 32000, tuitionMax: 44000, currency: 'AUD', ieltsMin: 6.0, ieltsOverall: 6.5, scholarship: true, scholarshipName: 'UQ Excellence Scholarship', scholarshipAmount: 'AUD 7,500', gpaMin: 2.8, intakes: ['Feb', 'Jul'], courses: ['Engineering', 'Science', 'Business', 'Health Sciences', 'IT', 'Law'], duration: '2–4 years', sopRequired: false, lorRequired: false, accommodationCost: 'AUD 600–1,100/mo', livingCost: 'AUD 1,500–2,000/mo', onCampus: true, partTimeHours: '48hrs/fortnight', postStudyVisa: '2–4 years', jobMarket: 'High', website: 'uq.edu.au', about: 'Research-intensive university in Brisbane — more affordable city than Sydney or Melbourne.' },
  { id: 105, name: 'RMIT University', country: 'Australia', flag: '🇦🇺', city: 'Melbourne', ranking: 140, image: 'https://images.unsplash.com/photo-1541339907198-e08756dedf3f?w=800&q=80', type: 'Public', established: 1887, tuitionMin: 28000, tuitionMax: 38000, currency: 'AUD', ieltsMin: 6.0, ieltsOverall: 6.0, scholarship: true, scholarshipName: 'RMIT Global Scholarship', scholarshipAmount: 'AUD 3,000', gpaMin: 2.5, intakes: ['Feb', 'Jul', 'Nov'], courses: ['Design', 'Engineering', 'IT', 'Business', 'Architecture', 'Fashion'], duration: '2–3 years', sopRequired: false, lorRequired: false, accommodationCost: 'AUD 700–1,200/mo', livingCost: 'AUD 1,600–2,200/mo', onCampus: false, partTimeHours: '48hrs/fortnight', postStudyVisa: '2 years', jobMarket: 'High', website: 'rmit.edu.au', about: 'Practical, industry-focused education. Strong in design, engineering and IT. 3 intakes per year.' },

  // CANADA
  { id: 201, name: 'University of Toronto', country: 'Canada', flag: '🇨🇦', city: 'Toronto', ranking: 21, image: 'https://images.unsplash.com/photo-1569523420547-b8ac5ce77543?w=800&q=80', type: 'Public', established: 1827, tuitionMin: 45000, tuitionMax: 68000, currency: 'CAD', ieltsMin: 6.5, ieltsOverall: 7.0, scholarship: true, scholarshipName: 'Lester B. Pearson Scholarship', scholarshipAmount: 'Full tuition + living', gpaMin: 3.5, intakes: ['Sep'], courses: ['Computer Science', 'Engineering', 'Medicine', 'Business', 'Law', 'Arts'], duration: '2–4 years', sopRequired: true, lorRequired: true, accommodationCost: 'CAD 900–1,600/mo', livingCost: 'CAD 1,800–2,500/mo', onCampus: true, partTimeHours: '20hrs/week', postStudyVisa: '3 years (PGWP)', jobMarket: 'Very High', website: 'utoronto.ca', about: "Canada's top university. Located in one of the world's most multicultural cities." },
  { id: 202, name: 'University of British Columbia', country: 'Canada', flag: '🇨🇦', city: 'Vancouver', ranking: 38, image: 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=800&q=80', type: 'Public', established: 1908, tuitionMin: 38000, tuitionMax: 55000, currency: 'CAD', ieltsMin: 6.5, ieltsOverall: 6.5, scholarship: true, scholarshipName: 'International Leader of Tomorrow', scholarshipAmount: 'Partial to full tuition', gpaMin: 3.3, intakes: ['Sep', 'Jan'], courses: ['Engineering', 'Forestry', 'Sciences', 'MBA', 'Computer Science', 'Film'], duration: '2–4 years', sopRequired: true, lorRequired: true, accommodationCost: 'CAD 1,000–1,800/mo', livingCost: 'CAD 2,000–2,800/mo', onCampus: true, partTimeHours: '20hrs/week', postStudyVisa: '3 years (PGWP)', jobMarket: 'Very High', website: 'ubc.ca', about: 'Stunning campus between mountains and ocean. Consistently top 40 globally.' },
  { id: 203, name: 'McGill University', country: 'Canada', flag: '🇨🇦', city: 'Montreal', ranking: 46, image: 'https://images.unsplash.com/photo-1562774053-701939374585?w=800&q=80', type: 'Public', established: 1821, tuitionMin: 28000, tuitionMax: 45000, currency: 'CAD', ieltsMin: 6.5, ieltsOverall: 7.0, scholarship: true, scholarshipName: 'McGill Entrance Scholarship', scholarshipAmount: 'CAD 3,000–12,000', gpaMin: 3.2, intakes: ['Sep', 'Jan'], courses: ['Medicine', 'Law', 'Engineering', 'Music', 'Science', 'Management'], duration: '2–4 years', sopRequired: true, lorRequired: true, accommodationCost: 'CAD 700–1,200/mo', livingCost: 'CAD 1,400–1,900/mo', onCampus: true, partTimeHours: '20hrs/week', postStudyVisa: '3 years (PGWP)', jobMarket: 'High', website: 'mcgill.ca', about: 'Harvard of Canada. Bilingual city, lower cost than Toronto. Strong medical and law programs.' },
  { id: 204, name: 'Seneca College', country: 'Canada', flag: '🇨🇦', city: 'Toronto', ranking: 0, image: 'https://images.unsplash.com/photo-1569523420547-b8ac5ce77543?w=800&q=80', type: 'College', established: 1967, tuitionMin: 15000, tuitionMax: 22000, currency: 'CAD', ieltsMin: 6.0, ieltsOverall: 6.0, scholarship: true, scholarshipName: 'International Student Award', scholarshipAmount: 'CAD 2,000', gpaMin: 2.3, intakes: ['Sep', 'Jan', 'May'], courses: ['Business', 'IT', 'Nursing', 'Accounting', 'Marketing', 'Project Management'], duration: '1–3 years', sopRequired: false, lorRequired: false, accommodationCost: 'CAD 800–1,400/mo', livingCost: 'CAD 1,500–2,000/mo', onCampus: false, partTimeHours: '20hrs/week', postStudyVisa: '1–3 years (PGWP)', jobMarket: 'High', website: 'senecacollege.ca', about: 'Most popular college for Nepali students. 3 intakes, practical programs, strong PR pathway.' },
  { id: 205, name: 'Humber College', country: 'Canada', flag: '🇨🇦', city: 'Toronto', ranking: 0, image: 'https://images.unsplash.com/photo-1562774053-701939374585?w=800&q=80', type: 'College', established: 1967, tuitionMin: 14000, tuitionMax: 20000, currency: 'CAD', ieltsMin: 6.0, ieltsOverall: 6.0, scholarship: false, scholarshipName: '', scholarshipAmount: '', gpaMin: 2.2, intakes: ['Sep', 'Jan', 'May'], courses: ['Business', 'Hospitality', 'Media', 'Design', 'IT', 'Social Services'], duration: '1–2 years', sopRequired: false, lorRequired: false, accommodationCost: 'CAD 800–1,400/mo', livingCost: 'CAD 1,500–2,000/mo', onCampus: true, partTimeHours: '20hrs/week', postStudyVisa: '1–3 years (PGWP)', jobMarket: 'High', website: 'humber.ca', about: 'Affordable college with strong industry connections. Great for PR pathway.' },

  // UK
  { id: 301, name: 'University of Oxford', country: 'UK', flag: '🇬🇧', city: 'Oxford', ranking: 1, image: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=800&q=80', type: 'Public', established: 1096, tuitionMin: 28950, tuitionMax: 39010, currency: 'GBP', ieltsMin: 7.0, ieltsOverall: 7.5, scholarship: true, scholarshipName: 'Rhodes Scholarship', scholarshipAmount: 'Full funding', gpaMin: 3.8, intakes: ['Oct'], courses: ['PPE', 'Medicine', 'Law', 'Computer Science', 'History', 'Engineering'], duration: '3–4 years', sopRequired: true, lorRequired: true, accommodationCost: 'GBP 600–1,000/mo', livingCost: 'GBP 1,200–1,600/mo', onCampus: true, partTimeHours: '20hrs/week', postStudyVisa: '2 years Graduate', jobMarket: 'Very High', website: 'ox.ac.uk', about: "World's oldest English-speaking university. Exceptional tutorial system." },
  { id: 302, name: 'University of Manchester', country: 'UK', flag: '🇬🇧', city: 'Manchester', ranking: 28, image: 'https://images.unsplash.com/photo-1529655683826-aba9b3e77383?w=800&q=80', type: 'Public', established: 1824, tuitionMin: 22000, tuitionMax: 32000, currency: 'GBP', ieltsMin: 6.0, ieltsOverall: 6.5, scholarship: true, scholarshipName: 'President\'s Doctoral Scholar Award', scholarshipAmount: 'Full tuition + stipend', gpaMin: 3.0, intakes: ['Sep', 'Jan'], courses: ['Business', 'Engineering', 'Computer Science', 'Life Sciences', 'Architecture', 'Law'], duration: '1–4 years', sopRequired: true, lorRequired: false, accommodationCost: 'GBP 500–900/mo', livingCost: 'GBP 1,000–1,400/mo', onCampus: true, partTimeHours: '20hrs/week', postStudyVisa: '2 years Graduate', jobMarket: 'High', website: 'manchester.ac.uk', about: 'Russell Group university, 25 Nobel laureates. Affordable city, popular for Nepali students.' },
  { id: 303, name: 'University of Hertfordshire', country: 'UK', flag: '🇬🇧', city: 'Hatfield', ranking: 801, image: 'https://images.unsplash.com/photo-1513635269975-59663e0ac1ad?w=800&q=80', type: 'Public', established: 1952, tuitionMin: 14000, tuitionMax: 18000, currency: 'GBP', ieltsMin: 5.5, ieltsOverall: 6.0, scholarship: true, scholarshipName: 'Vice Chancellor Scholarship', scholarshipAmount: 'GBP 2,000', gpaMin: 2.3, intakes: ['Sep', 'Jan', 'Apr'], courses: ['Business', 'Nursing', 'Engineering', 'Computer Science', 'Psychology', 'Pharmacy'], duration: '1–3 years', sopRequired: false, lorRequired: false, accommodationCost: 'GBP 400–700/mo', livingCost: 'GBP 900–1,200/mo', onCampus: true, partTimeHours: '20hrs/week', postStudyVisa: '2 years Graduate', jobMarket: 'Medium', website: 'herts.ac.uk', about: 'Affordable UK university near London. Low IELTS requirement, 3 intakes per year. Popular among Nepali students.' },

  // USA
  { id: 401, name: 'MIT', country: 'USA', flag: '🇺🇸', city: 'Cambridge, MA', ranking: 1, image: 'https://images.unsplash.com/photo-1564981797816-1043664bf78d?w=800&q=80', type: 'Private', established: 1861, tuitionMin: 57986, tuitionMax: 57986, currency: 'USD', ieltsMin: 7.0, ieltsOverall: 7.5, scholarship: true, scholarshipName: 'MIT Need-Based Aid', scholarshipAmount: 'Meets 100% of need', gpaMin: 3.9, intakes: ['Sep'], courses: ['Computer Science', 'Engineering', 'Physics', 'Architecture', 'Economics', 'Management'], duration: '2–4 years', sopRequired: true, lorRequired: true, accommodationCost: 'USD 900–1,500/mo', livingCost: 'USD 2,000–2,800/mo', onCampus: true, partTimeHours: '20hrs/week on campus', postStudyVisa: '1–3 years OPT/STEM', jobMarket: 'Very High', website: 'mit.edu', about: "World's leading science and technology institution. Need-blind admissions." },
  { id: 402, name: 'University of Texas at Austin', country: 'USA', flag: '🇺🇸', city: 'Austin, TX', ranking: 67, image: 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=800&q=80', type: 'Public', established: 1883, tuitionMin: 38000, tuitionMax: 45000, currency: 'USD', ieltsMin: 6.5, ieltsOverall: 7.0, scholarship: true, scholarshipName: 'International Distinction Award', scholarshipAmount: 'USD 5,000/year', gpaMin: 3.2, intakes: ['Aug', 'Jan'], courses: ['Engineering', 'Business', 'Computer Science', 'Film', 'Law', 'Nursing'], duration: '2–4 years', sopRequired: true, lorRequired: true, accommodationCost: 'USD 700–1,200/mo', livingCost: 'USD 1,500–2,000/mo', onCampus: true, partTimeHours: '20hrs/week on campus', postStudyVisa: '1–3 years OPT', jobMarket: 'Very High', website: 'utexas.edu', about: 'Located in tech hub Austin. Strong engineering and business programs.' },

  // JAPAN
  { id: 501, name: 'Waseda University', country: 'Japan', flag: '🇯🇵', city: 'Tokyo', ranking: 201, image: 'https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?w=800&q=80', type: 'Private', established: 1882, tuitionMin: 1200000, tuitionMax: 1800000, currency: 'JPY', ieltsMin: 6.0, ieltsOverall: 6.5, scholarship: true, scholarshipName: 'Waseda Scholarship', scholarshipAmount: 'Full or partial tuition', gpaMin: 3.0, intakes: ['Apr', 'Sep'], courses: ['International Relations', 'Business', 'Engineering', 'Political Science', 'Japanese Studies', 'Law'], duration: '2–4 years', sopRequired: true, lorRequired: true, accommodationCost: 'JPY 50,000–100,000/mo', livingCost: 'JPY 100,000–150,000/mo', onCampus: true, partTimeHours: '28hrs/week', postStudyVisa: 'Job search visa available', jobMarket: 'High', website: 'waseda.jp', about: "One of Japan's most prestigious private universities in the heart of Tokyo." },
  { id: 502, name: 'Tokyo University of Science', country: 'Japan', flag: '🇯🇵', city: 'Tokyo', ranking: 400, image: 'https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=800&q=80', type: 'Private', established: 1881, tuitionMin: 1000000, tuitionMax: 1400000, currency: 'JPY', ieltsMin: 5.5, ieltsOverall: 6.0, scholarship: true, scholarshipName: 'MEXT Scholarship', scholarshipAmount: 'Full tuition + monthly allowance', gpaMin: 2.8, intakes: ['Apr'], courses: ['Science', 'Engineering', 'Pharmacy', 'Management', 'Computer Science', 'Chemistry'], duration: '2–4 years', sopRequired: true, lorRequired: false, accommodationCost: 'JPY 40,000–80,000/mo', livingCost: 'JPY 90,000–130,000/mo', onCampus: false, partTimeHours: '28hrs/week', postStudyVisa: 'Job search visa available', jobMarket: 'High', website: 'tus.ac.jp', about: 'Strong science and engineering focus. MEXT government scholarship available for Nepali students.' },

  // GERMANY
  { id: 601, name: 'Technical University of Munich', country: 'Germany', flag: '🇩🇪', city: 'Munich', ranking: 37, image: 'https://images.unsplash.com/photo-1467269204594-9661b134dd2b?w=800&q=80', type: 'Public', established: 1868, tuitionMin: 0, tuitionMax: 700, currency: 'EUR', ieltsMin: 0, ieltsOverall: 6.5, scholarship: true, scholarshipName: 'DAAD Scholarship', scholarshipAmount: 'EUR 861/month + travel', gpaMin: 3.0, intakes: ['Oct', 'Apr'], courses: ['Engineering', 'Computer Science', 'Natural Sciences', 'Business', 'Architecture', 'Data Science'], duration: '2–3 years', sopRequired: true, lorRequired: true, accommodationCost: 'EUR 500–900/mo', livingCost: 'EUR 900–1,300/mo', onCampus: false, partTimeHours: '120 days/yr', postStudyVisa: '18 months job seeker', jobMarket: 'Very High', website: 'tum.de', about: "Germany's top technical university. FREE tuition. BMW, Siemens, Allianz partnerships." },
  { id: 602, name: 'RWTH Aachen University', country: 'Germany', flag: '🇩🇪', city: 'Aachen', ranking: 106, image: 'https://images.unsplash.com/photo-1467269204594-9661b134dd2b?w=800&q=80', type: 'Public', established: 1870, tuitionMin: 0, tuitionMax: 700, currency: 'EUR', ieltsMin: 0, ieltsOverall: 6.0, scholarship: true, scholarshipName: 'DAAD / Deutschlandstipendium', scholarshipAmount: 'EUR 300–861/month', gpaMin: 2.8, intakes: ['Oct', 'Apr'], courses: ['Engineering', 'Computer Science', 'Natural Sciences', 'Mathematics', 'Architecture', 'Geosciences'], duration: '2–3 years', sopRequired: true, lorRequired: false, accommodationCost: 'EUR 350–650/mo', livingCost: 'EUR 750–1,000/mo', onCampus: false, partTimeHours: '120 days/yr', postStudyVisa: '18 months job seeker', jobMarket: 'Very High', website: 'rwth-aachen.de', about: "Europe's best technical university for engineering. Free tuition, affordable city." },

  // NEW ZEALAND
  { id: 701, name: 'University of Auckland', country: 'New Zealand', flag: '🇳🇿', city: 'Auckland', ranking: 87, image: 'https://images.unsplash.com/photo-1507699622108-4be3abd695ad?w=800&q=80', type: 'Public', established: 1883, tuitionMin: 32000, tuitionMax: 42000, currency: 'NZD', ieltsMin: 6.0, ieltsOverall: 6.5, scholarship: true, scholarshipName: 'Excellence Scholarship', scholarshipAmount: 'NZD 10,000', gpaMin: 3.0, intakes: ['Feb', 'Jul'], courses: ['Engineering', 'Business', 'Law', 'Arts', 'Medical Science', 'IT'], duration: '2–4 years', sopRequired: false, lorRequired: false, accommodationCost: 'NZD 700–1,200/mo', livingCost: 'NZD 1,400–1,900/mo', onCampus: true, partTimeHours: '20hrs/week', postStudyVisa: '1–3 years', jobMarket: 'Medium', website: 'auckland.ac.nz', about: "New Zealand's largest and highest ranked university. Safe, multicultural." },

  // SOUTH KOREA
  { id: 801, name: 'Seoul National University', country: 'South Korea', flag: '🇰🇷', city: 'Seoul', ranking: 36, image: 'https://images.unsplash.com/photo-1601621915196-2621bfb0cd6e?w=800&q=80', type: 'Public', established: 1946, tuitionMin: 3000000, tuitionMax: 6000000, currency: 'KRW', ieltsMin: 0, ieltsOverall: 6.0, scholarship: true, scholarshipName: 'GKS Government Scholarship', scholarshipAmount: 'Full tuition + monthly allowance', gpaMin: 3.0, intakes: ['Mar', 'Sep'], courses: ['Engineering', 'Business', 'Medicine', 'Liberal Arts', 'Computer Science', 'Law'], duration: '2–4 years', sopRequired: true, lorRequired: true, accommodationCost: 'KRW 300,000–600,000/mo', livingCost: 'KRW 700,000–1,100,000/mo', onCampus: true, partTimeHours: '20hrs/week', postStudyVisa: 'D-10 job search', jobMarket: 'Medium', website: 'snu.ac.kr', about: "South Korea's most prestigious university. GKS scholarship covers everything." },
]

export const extendedCourses = [
  // STUDY courses
  { id: 'it', name: 'Computer Science / IT', category: 'study', demand: 'Very High', salary: '$60K–$120K', prChance: 'High', ieltsMin: 6.0, icon: '💻', duration: '2–4 years', desc: 'Software development, data science, cybersecurity, AI/ML', countries: ['Australia', 'Canada', 'Germany', 'USA', 'UK'], jobTitles: ['Software Developer', 'Data Analyst', 'Cybersecurity Engineer', 'AI Engineer', 'DevOps'] },
  { id: 'nursing', name: 'Nursing / Healthcare', category: 'study', demand: 'Very High', salary: '$55K–$95K', prChance: 'Very High', ieltsMin: 7.0, icon: '🏥', duration: '2–4 years', desc: 'Registered nurse, healthcare management, pharmacy, midwifery', countries: ['Australia', 'Canada', 'UK', 'New Zealand'], jobTitles: ['Registered Nurse', 'Midwife', 'Pharmacist', 'Healthcare Manager', 'ICU Nurse'] },
  { id: 'business', name: 'Business / MBA', category: 'study', demand: 'High', salary: '$50K–$100K', prChance: 'Medium', ieltsMin: 6.5, icon: '💼', duration: '1–2 years', desc: 'Business management, finance, supply chain, HR, marketing', countries: ['Australia', 'Canada', 'UK', 'USA', 'Germany'], jobTitles: ['Business Analyst', 'Project Manager', 'Finance Manager', 'HR Manager', 'Marketing Manager'] },
  { id: 'engineering', name: 'Engineering', category: 'study', demand: 'High', salary: '$60K–$110K', prChance: 'High', ieltsMin: 6.0, icon: '⚙️', duration: '2–4 years', desc: 'Civil, mechanical, electrical, chemical, software engineering', countries: ['Australia', 'Canada', 'Germany', 'UK'], jobTitles: ['Civil Engineer', 'Mechanical Engineer', 'Electrical Engineer', 'Project Engineer', 'Site Manager'] },
  { id: 'hospitality', name: 'Hospitality / Tourism', category: 'study', demand: 'Medium', salary: '$40K–$65K', prChance: 'Medium', ieltsMin: 5.5, icon: '🏨', duration: '1–2 years', desc: 'Hotel management, event management, culinary arts, tourism', countries: ['Australia', 'Canada', 'UK', 'New Zealand'], jobTitles: ['Hotel Manager', 'Events Coordinator', 'Tourism Manager', 'F&B Manager', 'Chef'] },
  { id: 'accounting', name: 'Accounting / Finance', category: 'study', demand: 'High', salary: '$55K–$90K', prChance: 'High', ieltsMin: 6.0, icon: '📊', duration: '2–3 years', desc: 'CPA, financial analysis, banking, taxation, auditing', countries: ['Australia', 'Canada', 'UK'], jobTitles: ['Accountant', 'Financial Analyst', 'Auditor', 'Tax Consultant', 'CPA'] },
  { id: 'education', name: 'Education / Teaching', category: 'study', demand: 'High', salary: '$45K–$75K', prChance: 'High', ieltsMin: 7.0, icon: '📚', duration: '1–2 years', desc: 'Teaching degree, early childhood, special education, TESOL', countries: ['Australia', 'Canada', 'UK', 'New Zealand'], jobTitles: ['Primary Teacher', 'ESL Teacher', 'Early Childhood Educator', 'School Counsellor'] },
  { id: 'trades', name: 'Trades / Vocational', category: 'study', demand: 'Very High', salary: '$55K–$90K', prChance: 'Very High', ieltsMin: 5.0, icon: '🔧', duration: '1–2 years', desc: 'Electrician, plumber, welder, carpenter — Red Seal Canada', countries: ['Australia', 'Canada'], jobTitles: ['Electrician', 'Plumber', 'Welder', 'Carpenter', 'HVAC Technician'] },
  { id: 'design', name: 'Design / Creative Arts', category: 'study', demand: 'Medium', salary: '$40K–$80K', prChance: 'Low', ieltsMin: 6.0, icon: '🎨', duration: '2–3 years', desc: 'Graphic design, interior design, digital media, UX/UI', countries: ['Australia', 'Canada', 'UK', 'Germany'], jobTitles: ['Graphic Designer', 'UX Designer', 'Interior Designer', 'Art Director', 'Creative Director'] },
  { id: 'socialwork', name: 'Social Work / Community', category: 'study', demand: 'High', salary: '$45K–$70K', prChance: 'High', ieltsMin: 7.0, icon: '❤️', duration: '2–4 years', desc: 'Social work, community development, disability support, aged care', countries: ['Australia', 'Canada', 'New Zealand'], jobTitles: ['Social Worker', 'Community Worker', 'Disability Support', 'Aged Care Coordinator'] },
]
